### ISSUE TITLE
BootCamp support?

### ISSUE THREAD

**Issue by carlossless** [ameyrupji/thunderbolt-macpro-5-1#2]
Hi,

I have to say that I love the great documentation you created here! Thanks.

I was wondering though, if you tried using your thunderbolt peripherals in windows/bootcamp, if so were there any extra steps needed to get them running?

Personally, I don't know if I'm barking up the wrong tree, but I tried the MacPro7,1 thunderbolt driver in bootcamp, and it doesn't seem like it works.

Thanks.

**Comment by ameyrupji** [comment]
I have tried my Apple Thunderbolt Monitors with Bootcamp and they work perfectly! I usually restart from and to macOS before shutting down my Mac Pro as my RX 580 does not support boot screen and I have not OpenCored my system.

**Comment by carlossless** [comment]
Thanks for letting me know, I will try the same thing. Cheers!
