### ISSUE TITLE
Stuck on "Couldn't open device 1a86:5512. Error: Programmer initialization failed." in Terminal

### ISSUE THREAD

**Issue by swordsx48** [ameyrupji/thunderbolt-macpro-5-1#9]
Hi! Hope all are well!
I've been stuck on this Thunderbolt hunt non stop for almost 10 days now. Finally I figured flashing it was the way to go, however, I'm stuck on this error 
"Couldn't open device 1a86:5512.
Error: Programmer initialization failed."
![Screenshot from 2021-03-28 20-51-00](https://user-images.githubusercontent.com/28914491/112784788-5a5ac100-9007-11eb-8c33-e0e1ae1c4051.png)

I've tried Ubuntu, macOS Mojave, and a Live USB of Fedora as someone mentioned that fixed this problem in the Google hunt for this issue. I tried those 3 on my desktop and then Mojave on my MacBook Pro. All the same error.
I'm stumped. I made this decision to flash them and I didn't expect these roadblocks. In fact, even getting flashrom to run was a bit of a journey because I had trouble with the libusb. That part was sovled. Thankfully there are you good people to advise.
I hope again I can get some resolution here. 

Thanks in advance!

**Comment by swordsx48** [comment]
Solved, needed to order a new piece, faulty unit. So I figured as well.

**Comment by MrLutik** [comment]
Try to use USB 3.0 instead. The blue usb port

**Comment by webtag-well** [comment]
> Solved, needed to order a new piece, faulty unit. So I figured as well.

Me too,but I have no problem using Asprogrammer tools .


err code:

PS C:\SNANDer_V1.7.9> .\SNANDer_x64_ys.exe -i

SNANDer - Serial Nor/nAND/Eeprom programmeR v.1.7.9 by McMCC <mcmcc@mail.ru>

Couldn't open device 1a86:5512.
Programmer device not found!
